---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: pai-highcharts-deployment
    owner: eng-app-infra
  name: pai-highcharts-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      run: pai-highcharts
  template:
    metadata:
      labels:
        run: pai-highcharts
        owner: eng-app-infra
    spec:
      containers:
      - command:
        - /app/docker-entrypoint.sh
        image: {{deploy_docker_registry}}/highcharts-export-server:{{deploy_build_num}}
        imagePullPolicy: IfNotPresent
        name: pai-highcharts
        resources:
          requests:
            cpu: 1
            memory: 2500Mi
          limits:
            cpu: 1
            memory: 2500Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pai-highcharts-deployment
  name: pai-highcharts-service
spec:
  ports:
  - port: 3003
    protocol: TCP
    targetPort: 3003
  selector:
    run: pai-highcharts
